### ISSUE TITLE
Monitor site traffic

### ISSUE THREAD

**Issue by kofiav** [bhklab/PharmacoDB-web#45]
Accurate site traffic metrics will assist us when writing the publication (low priority right now).

**Comment by kofiav** [comment]
PharmacoDB is running on `Rails development` in the pmgenomics server. We have to change the Google Analytics flag from if `Rails.env.production?` to `if Rails.env.development?`

**Comment by kofiav** [comment]
Fixed in 5e904d230fa940515856b80c05bf17efd5fe4802

**Comment by assefamaru** [comment]
@kofiav would it perhaps be better practice to talk with Qun so that he deploys the app in production mode (probably doing something like `rails s -e production` or something equivalent) instead of development? Because with production mode, we get things like class caching and asset compilation that wouldn't otherwise be present in development mode (and would make the app more performant).

**Comment by kofiav** [comment]
Yes, I agree - it would be easier if we ran the app in production mode. I'll keep chatting with Qun and keep you posted on the status.

**Comment by assefamaru** [comment]
@kofiav Sounds good.
